run1:
	py.test -v hello.py

run2:
	python -m pytest hello.py

run3:
	py.test --pdb -v hello.py # this will stop running when an assertion error occurred. For breakpoint setting, pytest.set_trace() should be called in the source file. It seems impossible to start pdb at the begining

run4:
	py.test -v hello_with_trace.py
